using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PenskeSampleSdk.Shared.ViewModel_Dto
{

    /// <summary>
    /// API Response
    /// </summary>
    public class ApiResponse<T>
    {
        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this response.
        /// </summary>
        /// <value>The status code.</value>
        public int Status { get; private set; }

        /// <summary>
        /// Gets or sets the data (parsed HTTP body)
        /// </summary>
        /// <value>The data.</value>
        public T Data { get; private set; }

        /// <summary>
        /// ExtendedData used for additional properties when needed. 
        /// </summary>
        public IDictionary<string, object> ExtendedData { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiResponse&lt;T&gt;" /> class.
        /// </summary>
        /// <param name="status">HTTP status code.</param>
        /// <param name="headers">HTTP headers.</param>
        /// <param name="data">Data (parsed HTTP body)</param>
        /// <param name="metaData">Dictionary to Hold metaData</param>
        public ApiResponse(int status, T data)
        {
            Status = status;
            Data = data;
        }

    }
}
